on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: digitcontainerregistry.azurecr.io
        username: ${{ secrets.acr_digitcontainerregistry_username }}
        password: ${{ secrets.acr_digitcontainerregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t digitcontainerregistry.azurecr.io/akstest:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push digitcontainerregistry.azurecr.io/akstest:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_akstest_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks-test-camund | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks-test-camund`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks-test-camund
        container-registry-url: digitcontainerregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_digitcontainerregistry_username }}
        container-registry-password: ${{ secrets.acr_digitcontainerregistry_password }}
        secret-name: akstestdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks-test-camund
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          digitcontainerregistry.azurecr.io/akstest:${{ github.sha }}
        imagepullsecrets: |
          akstestdockerauth
